name: Elixir Quality Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  quality_checks:
    name: Formatting, Credo, and Unused Deps
    runs-on: ubuntu-latest
    env:
      MIX_ENV: dev
      elixir: "1.18.4"
      otp: "27.3.4.2"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Elixir Project
        uses: ./.github/actions/elixir-setup
        with:
          elixir-version: ${{ env.elixir }}
          otp-version: ${{ env.otp }}
          build-app: false

      - name: Check for unused deps
        run: mix deps.unlock --check-unused
      - name: Check code formatting
        run: mix format --check-formatted
        # Check formatting even if there were unused deps so that
        # we give devs as much feedback as possible & save some time.
        if: always()
      - name: Run Credo
        run: mix credo suggest --min-priority=normal
        # Run Credo even if formatting or the unused deps check failed
        if: always()
      - name: Check for compile-time dependencies
        run: mix xref graph --label compile-connected --fail-above 0
        if: always()
